# Custom Language File for Launcher Customizer

[ejs.app]
title = "힐링타운"

[ejs.landing]
mediaGitHubURL = "#"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/7zBr4rBpeF"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/MrJimin/HealingTownLauncher"
supportLink = "https://github.com/MrJimin/HealingTownLauncher/issues"

[ejs.welcome]
welcomeHeader = "힐링타운"
welcomeDescription = "서버에 오신것을 환영합니다!"
welcomeDescCTA = "계속하기 버튼을 눌러 계속 진행하여 주세요."
